#!/bin/sh
export LD_LIBRARY_PATH=/usr/lib/oracle/12.1/client64/lib
sqlplus64 "pkamboj/09084588@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(Host=oracle.scs.ryerson.ca)(Port=1521))(CONNECT_DATA=(SID=orcl)))"<<EOF
	DROP TABLE CUSTOMER;
	DROP TABLE EMPLOYEE;
	DROP TABLE EXCHANGE;
	DROP TABLE PRODUCT;
	DROP TABLE PURCHASE;
	DROP TABLE RETURN;
	DROP TABLE STORE;
	DROP TABLE TRANSACTION;
	DROP TABLE STOREOnline;
	DROP TABLE CUSTOMERContactinfo;
	DROP TABLE TRANSACTIONInfo;
	DROP TABLE PRODUCTInfo;

	exit;
EOF
