#!/bin/sh
export LD_LIBRARY_PATH=/usr/lib/oracle/12.1/client64/lib
sqlplus64 "pkamboj/09084588@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(Host=oracle.scs.ryerson.ca)(Port=1521))(CONNECT_DATA=(SID=orcl)))"<<EOF

/* STORE */
SELECT STORENAME, 'Store number is: ',STORENUMBER
FROM   STORE;

/* STORE ONLINE - NEW (DUE TO 3NF) */
SELECT 'Store Website is: ',STOREWEBSITE
FROM   STOREONLINE;

/* EMPLOYEES */
SELECT SIN, BANKACCOUNTNUMBER
FROM EMPLOYEE
ORDER BY SIN DESC, BANKACCOUNTNUMBER ASC;

/* CUSTOMERS */
SELECT DISTINCT CUSTOMERFULLNAME, CUSTOMERPHONENUMBER
FROM CUSTOMER
ORDER BY CUSTOMERFULLNAME;

/* CUSTOMER CONTACT INFO - NEW (DUE TO 3NF) */
SELECT DISTINCT CUSTOMERPHONENUMBER
FROM CUSTOMERCONTACTINFO
ORDER BY CUSTOMERPHONENUMBER;

/* PRODUCTS */
SELECT DISTINCT PRODUCTSERIALNUMBER,  PRODUCTPRICE
FROM PRODUCT
WHERE PRODUCTPRICE <= 50;

/* TRANSACTIONS */
SELECT TRANSACTIONMETHOD 
FROM TRANSACTION
WHERE TRANSACTIONMETHOD <>  'Debit';

/* TRANSACTION INFO - NEW (DUE TO 3NF) */
SELECT PRODUCTSERIALNUMBER, TRANSACTIONNUMBER
FROM TRANSACTIONINFO;

/* EXCHANGE */
SELECT *
FROM exchange
ORDER BY transactionnumber DESC;

/* RETURN */
SELECT *
FROM RETURN
WHERE transactionnumber <= 200000000;

/* PURCHASE */
SELECT *
FROM PURCHASE
WHERE transactionnumber >= 700000000;

/* Assignment 9 Quiries */

/*PRODUCT INFO - NEW (DUE TO 3NF) */
SELECT SUM(PRODUCTPRICE)
FROM PRODUCTinfo
WHERE PRODUCTPRICE >= 20;

/* Assignment 9 Quiries */
SELECT PRODUCTPRICE
FROM PRODUCTinfo
WHERE PRODUCTPRICE >= 20;


exit;
EOF
